import { ObjectId } from 'mongodb';
import { Document } from 'mongoose';

export interface ISearch extends Document {
  /**
   * unique ID for document
   */
  _id: ObjectId;

  // generated by mongoose
  /**
   * create time of this document
   */
  createdAt: Date;

  /**
   * update time of this document
   */
  updatedAt: Date;
}
